name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine pytest

      - name: Verify tag matches version
        run: |
          VERSION=$(python - <<'PY'
          import re, pathlib
          text = pathlib.Path('simplepasswordguard/__init__.py').read_text(encoding='utf-8')
          m = re.search(r"__version__\s*=\s*['\"]([^'\"]+)['\"]", text)
          assert m, "__version__ not found"
          print(m.group(1))
          PY
          )
          echo "Package version: $VERSION"
          echo "Git tag: ${GITHUB_REF_NAME}"
          if [[ "${GITHUB_REF_NAME}" != "v${VERSION}" && "${GITHUB_REF_NAME}" != "${VERSION}" ]]; then
            echo "Tag ${GITHUB_REF_NAME} does not match version ${VERSION}"
            exit 1
          fi

      - name: Run tests
        run: |
          python -m pip install -e .
          pytest -q

      - name: Build sdist and wheel
        run: |
          python -m build
          python -m twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

